name: Sync metadata

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: List files
        run: ls

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.SIGN_PRIVATE_KEY }}

      - name: Sign Files
        run: |
          pwsh -ep bypass ./tools/sign.ps1

      - name: Upload file to alist
        env: # Or as an environment variable
          ALIST_HOST: ${{ secrets.ALIST_HOST }}
          ALIST_KEY: ${{ secrets.ALIST_KEY }}
        run: |
          pwsh -ep bypass ./tools/upload-alist.ps1 ./out/ ClassIsland-Ningbo-S3/classisland/
